spring.application.name=users
spring.datasource.url=jdbc:postgresql://medplus-stage.rds.com:5432/nidhijoshi
spring.datasource.username=postgres
spring.datasource.password=abcsdjshd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7070/realms/doctor-app

